Don't fail silently if .init isn't a function #cuttingFeatures
Because of the check for inheriting a non-pjs class, the only way for
that to happen is if you monkey-patch .init to something that isn't a
function, in which case you'll get a

    TypeError: Object ${thing you monkey-patched .init to} has no method 'apply'

which I feel like is excellent behavior.

<0.4kb now!